In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [4]:
ames = pd.read_csv('/Users/jenelleverrochi/Desktop/DSI/Train Data - Project 3.txt')
ames_test = pd.read_csv('/Users/jenelleverrochi/Desktop/DSI/Test Data - Project 3.txt')

In [5]:
g = ames.columns.to_series().groupby(ames.dtypes).groups
d = {k.name: v for k, v in g.items()}
d

{'float64': Index(['Lot Frontage', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2',
        'Bsmt Unf SF', 'Total Bsmt SF', 'Bsmt Full Bath', 'Bsmt Half Bath',
        'Garage Yr Blt', 'Garage Cars', 'Garage Area'],
       dtype='object'),
 'int64': Index(['Id', 'PID', 'MS SubClass', 'Lot Area', 'Overall Qual', 'Overall Cond',
        'Year Built', 'Year Remod/Add', '1st Flr SF', '2nd Flr SF',
        'Low Qual Fin SF', 'Gr Liv Area', 'Full Bath', 'Half Bath',
        'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces',
        'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
        'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold',
        'SalePrice'],
       dtype='object'),
 'object': Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
        'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
        'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
        'Exterior 1st', 'Exterior 2n

In [6]:
ames_num = ames[['Lot Frontage', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2',
        'Bsmt Unf SF', 'Total Bsmt SF', 'Bsmt Full Bath', 'Bsmt Half Bath',
        'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Id', 'PID', 'MS SubClass', 'Lot Area', 'Overall Qual', 'Overall Cond',
        'Year Built', 'Year Remod/Add', '1st Flr SF', '2nd Flr SF',
        'Low Qual Fin SF', 'Gr Liv Area', 'Full Bath', 'Half Bath',
        'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces',
        'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
        'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold' ]]

ames_cat = ames[['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
        'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
        'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
        'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual',
        'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
        'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC',
        'Central Air', 'Electrical', 'Kitchen Qual', 'Functional',
        'Fireplace Qu', 'Garage Type', 'Garage Finish', 'Garage Qual',
        'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature',
        'Sale Type', 'Sale Condition']]

In [7]:
ames_cat['Sale Condition'].value_counts()

Normal     1696
Partial     164
Abnorml     132
Family       29
Alloca       19
AdjLand      11
Name: Sale Condition, dtype: int64

In [8]:
# 1=abnormal and 0=not abnormal

In [9]:
ames_cat['Sale Condition'] = [1 if x=='Abnorml' else 0 for x in ames_cat['Sale Condition']]


/Users/jenelleverrochi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [10]:
ames_cat['Sale Condition'].value_counts()

0    1919
1     132
Name: Sale Condition, dtype: int64

In [11]:
X = ames_num
y = ames_cat['Sale Condition']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1538, 38) (513, 38) (1538,) (513,)


In [13]:
X_train.isnull().sum()[X_train.isnull().sum()>0]

Lot Frontage      239
Mas Vnr Area       15
BsmtFin SF 1        1
BsmtFin SF 2        1
Bsmt Unf SF         1
Total Bsmt SF       1
Bsmt Full Bath      2
Bsmt Half Bath      2
Garage Yr Blt      87
Garage Cars         1
Garage Area         1
dtype: int64

In [14]:
from sklearn.preprocessing import Imputer
imputer = Imputer(strategy='median')

X_train = imputer.fit_transform(X_train)

In [15]:
X_train

array([[   68.,   451.,   569., ...,     0.,     6.,  2010.],
       [   80.,    39.,   528., ...,     0.,    12.,  2008.],
       [   73.,     0.,   708., ...,     0.,     7.,  2006.],
       ..., 
       [   73.,     0.,    16., ...,     0.,     7.,  2009.],
       [   80.,   125.,   380., ...,     0.,     9.,  2006.],
       [   68.,   120.,   527., ...,     0.,     6.,  2008.]])

In [16]:
ss = StandardScaler()
ss.fit(X_train)
X_train = ss.transform(X_train)

X_train

array([[-0.05994568,  2.09726548,  0.30543841, ..., -0.11330669,
        -0.05748512,  1.72029826],
       [ 0.48748504, -0.3409686 ,  0.21409183, ..., -0.11330669,
         2.17139168,  0.18292538],
       [ 0.16815045, -0.57177231,  0.6151256 , ..., -0.11330669,
         0.31399435, -1.3544475 ],
       ..., 
       [ 0.16815045, -0.57177231, -0.92662646, ..., -0.11330669,
         0.31399435,  0.95161182],
       [ 0.48748504,  0.16798318, -0.11564705, ..., -0.11330669,
         1.05695328, -1.3544475 ],
       [-0.05994568,  0.13839296,  0.21186387, ..., -0.11330669,
        -0.05748512,  0.18292538]])

In [17]:
X_train = pd.DataFrame(X_train, columns=X.columns)

In [18]:
from sklearn.linear_model import Lasso, LinearRegression, LogisticRegression, ElasticNet
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split
from sklearn.feature_selection import RFE, SelectKBest, f_classif, f_regression

In [19]:
logreg = LogisticRegression(C=1000000)
logreg.fit(X_train, y_train)

LogisticRegression(C=1000000, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [20]:
logreg.coef_.shape

(1, 38)

In [21]:
sx_list = []
for i, col in enumerate(X_train):
    if logreg.coef_[0,i]!=0:
        sx_list.append(col)
        print(col, logreg.coef_[0,i])

Lot Frontage -0.0480314930924
Mas Vnr Area 0.21957812821
BsmtFin SF 1 -24.201067381
BsmtFin SF 2 -8.95010519641
Bsmt Unf SF -23.8273655184
Total Bsmt SF 23.4742662274
Bsmt Full Bath -0.0366421885153
Bsmt Half Bath 0.0684377150811
Garage Yr Blt -0.168876622714
Garage Cars -0.598973635303
Garage Area 0.47925754568
Id 0.565065977262
PID -0.0695481294171
MS SubClass 0.205415831638
Lot Area 0.0260942838975
Overall Qual -0.331213172881
Overall Cond -0.300341145774
Year Built -0.139859465812
Year Remod/Add 0.106357033014
1st Flr SF 0.197386126196
2nd Flr SF 0.0338004981028
Low Qual Fin SF 0.0856619668784
Gr Liv Area 0.192306735967
Full Bath -0.406224024588
Half Bath -0.198399744823
Bedroom AbvGr -0.103076632978
Kitchen AbvGr -0.00250977625038
TotRms AbvGrd 0.193650135205
Fireplaces -0.270448797815
Wood Deck SF -0.312496356035
Open Porch SF 0.169702252634
Enclosed Porch 0.074869456482
3Ssn Porch -0.0295607004536
Screen Porch -0.0392450849131
Pool Area -1.76999907642
Misc Val -0.255169458206
Mo

In [22]:
sx_list

['Lot Frontage',
 'Mas Vnr Area',
 'BsmtFin SF 1',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Garage Yr Blt',
 'Garage Cars',
 'Garage Area',
 'Id',
 'PID',
 'MS SubClass',
 'Lot Area',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'TotRms AbvGrd',
 'Fireplaces',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Misc Val',
 'Mo Sold',
 'Yr Sold']

In [23]:
selected_X= X_train[sx_list]

In [24]:
selected_X.head()

Lot Frontage  Mas Vnr Area  BsmtFin SF 1  BsmtFin SF 2  Bsmt Unf SF  \
0     -0.059946      2.097265      0.305438      0.191276     0.255786   
1      0.487485     -0.340969      0.214092     -0.294224    -0.192124   
2      0.168150     -0.571772      0.615126     -0.294224    -1.033652   
3      2.768446      5.997256      1.432789     -0.294224    -0.364049   
4      0.898058      0.315934     -0.873155     -0.294224     1.898121   

   Total Bsmt SF  Bsmt Full Bath  Bsmt Half Bath  Garage Yr Blt  Garage Cars  \
0       0.646505        1.106287       -0.252471      -0.615349     0.305192   
1      -0.087190        1.106287       -0.252471      -0.018146     0.305192   
2      -0.527408        1.106287       -0.252471      -0.854230    -1.005942   
3       0.992717        1.106287       -0.252471       0.897564     1.616327   
4       0.912469        1.106287       -0.252471      -1.053297    -1.005942   

     ...     Fireplaces  Wood Deck SF  Open Porch SF  Enclosed Porch  \
0    ...       2.203998     -0.728114      -0.319034       -0.381421   
1    ...       0.638294      0.557220      -0.720517       -0.381421   
2    ...      -0.927410     -0.728114      -0.720517       -0.381421   
3    ...       0.638294     -0.728114       0.205983       -0.381421   
4    ...       0.638294     -0.728114      -0.102851        4.895281   

   3Ssn Porch  Screen Porch  Pool Area  Misc Val   Mo Sold   Yr Sold  
0   -0.102037     -0.288711  -0.073356 -0.113307 -0.057485  1.720298  
1   -0.102037     -0.288711  -0.073356 -0.113307  2.171392  0.182925  
2   -0.102037     -0.288711  -0.073356 -0.113307  0.313994 -1.354447  
3   -0.102037     -0.288711  -0.073356 -0.113307 -1.914882  0.182925  
4   -0.102037     -0.288711  -0.073356 -0.113307  0.313994 -1.354447  

[5 rows x 38 columns]

In [25]:
print('All features')
scores = cross_val_score(logreg, X_train, y_train)
print(scores, '\n', 'Mean: ', scores.mean())

print('Feature Selection via Regularization')
scores = cross_val_score(logreg, selected_X, y_train)
print(scores, '\n', 'Mean: ', scores.mean())

All features
[ 0.94346979  0.93957115  0.94335938] 
 Mean:  0.942133436891
Feature Selection via Regularization
[ 0.94346979  0.93957115  0.94335938] 
 Mean:  0.942133436891


In [26]:
#Must impute and standardize X_test

In [27]:
X_test = imputer.transform(X_test)
X_test = pd.DataFrame(X_test, columns=X.columns)

In [28]:
ss = StandardScaler()
ss.fit(X_test)
X_test = ss.transform(X_test)

In [29]:
X_test = pd.DataFrame(X_test, columns=X.columns)
X_test.head()

Lot Frontage  Mas Vnr Area  BsmtFin SF 1  BsmtFin SF 2  Bsmt Unf SF  \
0      0.020722      0.419413     -0.886696      5.185767     0.727049   
1     -0.394129     -0.553224     -0.957502     -0.279764    -0.123572   
2     -0.394129     -0.553224     -0.957502     -0.279764     0.044343   
3     -0.705267     -0.172627      1.025062     -0.028186    -1.069196   
4      0.020722     -0.553224      1.516658     -0.279764    -0.293696   

   Total Bsmt SF  Bsmt Full Bath  Bsmt Half Bath  Garage Yr Blt  Garage Cars  \
0       1.476476        1.068759       -0.251075      -1.140277     0.253848   
1      -1.184244       -0.796116       -0.251075      -1.950178    -1.048392   
2      -1.027367       -0.796116       -0.251075      -2.376442     0.253848   
3       0.037747        1.068759       -0.251075       0.309021     0.253848   
4       1.181299        1.068759       -0.251075       0.820537     0.253848   

     ...     Fireplaces  Wood Deck SF  Open Porch SF  Enclosed Porch  \
0    ...       2.217385      0.626186       0.965452        3.139795   
1    ...      -0.920597     -0.738526       0.550241       -0.365688   
2    ...      -0.920597      1.053686      -0.695390       -0.365688   
3    ...       0.648394      0.289119      -0.695390       -0.365688   
4    ...      -0.920597      0.617965       0.024308       -0.365688   

   3Ssn Porch  Screen Porch  Pool Area  Misc Val   Mo Sold   Yr Sold  
0   -0.116209     -0.285579        0.0 -0.102432  1.242164 -0.608327  
1   -0.116209     -0.285579        0.0 -0.102432 -0.490381  0.136474  
2   -0.116209      3.548596        0.0 -0.102432  1.242164 -1.353128  
3   -0.116209     -0.285579        0.0 -0.102432  0.202637 -1.353128  
4   -0.116209     -0.285579        0.0 -0.102432  1.935182  0.136474  

[5 rows x 38 columns]

In [30]:
selected_x_test = X_test[sx_list]
selected_x_test.shape

(513, 38)

In [31]:
y_test.shape

(513,)

In [32]:
print('All features')
scores = cross_val_score(logreg, X_test, y_test)
print(scores, '\n', 'Mean: ', scores.mean())


print('Feature Selection via Regularization')
scores = cross_val_score(logreg, selected_x_test, y_test)
print(scores, '\n', 'Mean: ', scores.mean())

All features
[ 0.88953488  0.85380117  0.90588235] 
 Mean:  0.883072802084
Feature Selection via Regularization
[ 0.88953488  0.85380117  0.90588235] 
 Mean:  0.883072802084


### Predicting

In [33]:
ames_test.shape

(879, 80)

In [34]:
ames_test.isnull().sum()[ames_test.isnull().sum()> 0]

Lot Frontage      160
Alley             821
Mas Vnr Type        1
Mas Vnr Area        1
Bsmt Qual          25
Bsmt Cond          25
Bsmt Exposure      25
BsmtFin Type 1     25
BsmtFin Type 2     25
Electrical          1
Fireplace Qu      422
Garage Type        44
Garage Yr Blt      45
Garage Finish      45
Garage Qual        45
Garage Cond        45
Pool QC           875
Fence             707
Misc Feature      838
dtype: int64

In [35]:
ames_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 879 entries, 0 to 878
Data columns (total 80 columns):
Id                 879 non-null int64
PID                879 non-null int64
MS SubClass        879 non-null int64
MS Zoning          879 non-null object
Lot Frontage       719 non-null float64
Lot Area           879 non-null int64
Street             879 non-null object
Alley              58 non-null object
Lot Shape          879 non-null object
Land Contour       879 non-null object
Utilities          879 non-null object
Lot Config         879 non-null object
Land Slope         879 non-null object
Neighborhood       879 non-null object
Condition 1        879 non-null object
Condition 2        879 non-null object
Bldg Type          879 non-null object
House Style        879 non-null object
Overall Qual       879 non-null int64
Overall Cond       879 non-null int64
Year Built         879 non-null int64
Year Remod/Add     879 non-null int64
Roof Style         879 non-null object
Roof M

In [36]:
g = ames_test.columns.to_series().groupby(ames.dtypes).groups
d = {k.name: v for k, v in g.items()}
d

{'float64': Index(['Lot Frontage', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2',
        'Bsmt Unf SF', 'Total Bsmt SF', 'Bsmt Full Bath', 'Bsmt Half Bath',
        'Garage Yr Blt', 'Garage Cars', 'Garage Area'],
       dtype='object'),
 'int64': Index(['Id', 'PID', 'MS SubClass', 'Lot Area', 'Overall Qual', 'Overall Cond',
        'Year Built', 'Year Remod/Add', '1st Flr SF', '2nd Flr SF',
        'Low Qual Fin SF', 'Gr Liv Area', 'Full Bath', 'Half Bath',
        'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces',
        'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
        'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold'],
       dtype='object'),
 'object': Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
        'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
        'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
        'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', '

In [37]:
ames_test_num = ames_test[['Lot Frontage', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2',
        'Bsmt Unf SF', 'Total Bsmt SF', 'Bsmt Full Bath', 'Bsmt Half Bath',
        'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Id', 'PID', 'MS SubClass', 'Lot Area', 'Overall Qual', 'Overall Cond',
        'Year Built', 'Year Remod/Add', '1st Flr SF', '2nd Flr SF',
        'Low Qual Fin SF', 'Gr Liv Area', 'Full Bath', 'Half Bath',
        'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces',
        'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
        'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold']]

In [38]:
ames_test_num.shape

(879, 38)

In [39]:
ames_test_ss = imputer.transform(ames_test_num)
ames_test_ss = pd.DataFrame(ames_test_ss)

In [40]:
ss = StandardScaler()
ss.fit(ames_test_ss)
ames_test_ss = ss.transform(ames_test_ss)

In [41]:
ames_test_ss = pd.DataFrame(ames_test_ss, columns=ames_test_num.columns)

In [42]:
ames_test_ss.shape

(879, 38)

In [43]:
y_hat = logreg.predict(ames_test_ss)

In [44]:
PRED = pd.DataFrame(y_hat, columns=['Sale Condition'])
PRED['Sale Condition'].value_counts()

0    848
1     31
Name: Sale Condition, dtype: int64

In [45]:
ID = ames_test[['Id']]

In [46]:
Prediction = pd.concat([ID, PRED], axis=1)

In [47]:
Prediction.head()

Id  Sale Condition
0  2658               0
1  2718               0
2  2414               0
3  1989               0
4   625               0

In [48]:
y_test.value_counts()

0    470
1     43
Name: Sale Condition, dtype: int64

In [49]:
33/480

0.06875

In [50]:
y_train.value_counts()

0    1449
1      89
Name: Sale Condition, dtype: int64

In [51]:
99/1439

0.06879777623349548

In [52]:
39/840


0.04642857142857143

In [53]:
Prediction.to_csv('predictions_cl.csv', index=False)

In [54]:
logreg = LogisticRegression()
cross_val_score(logreg, X_test, y_test, cv=5).mean()

0.91227869788692184

In [55]:
from sklearn import svm

clf = svm.SVC()
print(cross_val_score(clf, X_train, y_train, cv=5).mean())


clf = svm.SVC(kernel= 'linear')
print(cross_val_score(clf, X_train, y_train, cv=5).mean())



0.942135642136
0.942135642136


In [81]:
clf.fit(X_train, y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [83]:
clf.score(X_test, y_test)

0.89278752436647169

In [84]:
y_hat2 = clf.predict(ames_test_ss)

In [91]:
PRED2 = pd.DataFrame(y_hat2, columns=['Sale Condition'])

In [92]:
Prediction2 = pd.concat([ID, PRED2], axis=1)

In [94]:
Prediction2.to_csv('predictions_cl2.csv', index=False)

In [134]:
knn = KNeighborsClassifier(n_neighbors=5, p=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=1,
           weights='uniform')

In [135]:
knn.score(X_train, y_train)

0.94148244473342002

In [136]:
knn.score(X_test, y_test)

0.91617933723196876

In [137]:
knn.predict(ames_test_ss).sum()

3

In [96]:
knn_best = knn_gs.best_estimator_
print(knn_gs.best_params_)
print(knn_gs.best_score_)

{'n_neighbors': 6, 'weights': 'uniform'}
0.942132639792


In [103]:
knn_gs.predict(X_test).sum()

0

In [104]:

from sklearn.linear_model import LogisticRegression

lr_params = {
    'penalty':['l1','l2'],
    'C':np.logspace(-4, 2, 40),
    'solver':['liblinear']
}

lr_gs = GridSearchCV(LogisticRegression(), lr_params, cv=5, verbose=1)
lr_gs.fit(X_train, y_train)

Fitting 5 folds for each of 80 candidates, totalling 400 fits


[Parallel(n_jobs=1)]: Done 400 out of 400 | elapsed:  1.7min finished


GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': array([  1.00000e-04,   1.42510e-04,   2.03092e-04,   2.89427e-04,
         4.12463e-04,   5.87802e-04,   8.37678e-04,   1.19378e-03,
         1.70125e-03,   2.42446e-03,   3.45511e-03,   4.92388e-03,
         7.01704e-03,   1.00000e-02,   1.42510e-02,   2.0...6e+01,
         3.45511e+01,   4.92388e+01,   7.01704e+01,   1.00000e+02]), 'solver': ['liblinear']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=1)

In [105]:
best_lr = lr_gs.best_estimator_
print(lr_gs.best_params_)
print(lr_gs.best_score_)

{'C': 0.24244620170823308, 'penalty': 'l2', 'solver': 'liblinear'}
0.94278283485


In [109]:
lr_gs.predict(ames_test_ss).sum()

3

In [142]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=10, random_state=0)
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [150]:
clf.score(X_test, y_test)

0.89083820662768032

In [148]:
Prediction3 = clf.predict(ames_test_ss)

In [153]:
Prediction3 = pd.DataFrame(Prediction3, columns=['Sale Condition'])

In [155]:
Prediction3 = pd.concat([ID, Prediction3], axis=1)

In [157]:
Prediction3.to_csv('prediction_cl3.csv', index=False)

In [158]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier

In [159]:
clf = DecisionTreeClassifier(max_depth=20)
bagger = BaggingClassifier(clf, n_estimators=10)

print('Decision Tree Score: ', cross_val_score(clf, X_train, y_train, cv=10).mean())
print('Bagging Score: ', cross_val_score(bagger, X_train, y_train, cv=10).mean())

Decision Tree Score:  0.895975734792
Bagging Score:  0.937593984962


In [160]:
cross_val_score(bagger, X_test, y_test, cv=10).mean()

0.90260180995475126

In [166]:
bagger.score(X_test, y_test)

0.91617933723196876

In [164]:
bagger.predict(ames_test_ss).sum()

2